In [6]:
import pandas as pd
import stats
import json

### Predicción de Sentimientos

In [10]:
# Macro F1 scores predicción de sentimientos

macro_values = {
    'BERT':    [[71.63,65.93 , 85.02],     
                [71.85 , 67.03, 84.56],     
                [71.85  , 68.83 , 85.55],     
                [75.00, 66.27 , 84.11],    
                [65.59 , 60.58 , 84.56] 
               ],
    'RoBERTa': [
        [68.10, 64.16, 85.65],
        [71.17, 64.32, 87.13],
        [77.58, 66.23, 85.86],
        [70.46, 64.36, 85.33],
        [41.66, 62.67, 86.85]
    ],
    'LLaMA': [
        [49.21, 66.37, 87.60],
        [78.10, 69.14, 88.24],
        [74.90, 67.75, 86.96],
        [68.75, 66.69, 88.84],
        [59.33, 69.64, 86.96]
    ],
    'DeepSeek': [
        [68.75, 52.50, 78.89],
        [42.31, 53.71, 79.90],
        [44.21, 50.59, 76.83],
        [49.21, 51.75, 78.00],
        [65.32, 53.52, 78.82]
    ]
}

a=0.05
modelos = ['BERT','RoBERTa', 'LLaMA', 'DeepSeek']
metodos = ['Baseline', 'SVD', 'DeepWalk', 'Node2Vec', 'TADW']
datasets = ['RT-MIND', 'HCR', 'OMC']


rows = []
index = []

for modelo in modelos:
    for metodo, valores in zip(metodos, macro_values[modelo]):
        index.append((modelo, metodo))
        rows.append(valores)


multi_index = pd.MultiIndex.from_tuples(index, names=[None, None])
df = pd.DataFrame(rows, index=multi_index, columns=datasets)

df

                   RT-MIND    HCR    OMC
BERT     Baseline    71.63  65.93  85.02
         SVD         71.85  67.03  84.56
         DeepWalk    71.85  68.83  85.55
         Node2Vec    75.00  66.27  84.11
         TADW        65.59  60.58  84.56
RoBERTa  Baseline    68.10  64.16  85.65
         SVD         71.17  64.32  87.13
         DeepWalk    77.58  66.23  85.86
         Node2Vec    70.46  64.36  85.33
         TADW        41.66  62.67  86.85
LLaMA    Baseline    49.21  66.37  87.60
         SVD         78.10  69.14  88.24
         DeepWalk    74.90  67.75  86.96
         Node2Vec    68.75  66.69  88.84
         TADW        59.33  69.64  86.96
DeepSeek Baseline    68.75  52.50  78.89
         SVD         42.31  53.71  79.90
         DeepWalk    44.21  50.59  76.83
         Node2Vec    49.21  51.75  78.00
         TADW        65.32  53.52  78.82

In [11]:
df = pd.DataFrame(rows, index=multi_index, columns=datasets)

a=0.05
df=df.reset_index()
df['features']=df['level_1']
df['classifier']=df['level_0']
df.drop(['level_0','level_1'], axis=1, inplace=True)

x, friedman_list = stats.main(df, a=a)
friedman_list

k: 20       N: 3       a: 0.05
chi2:  39.35238095238097
Friedman's F:  4.459794927145176
F(19,38)|0.05:  1.867331954702147

                           0
LLaMA SVD           1.666667
LLaMA DeepWalk           4.5
LLaMA Node2Vec      5.833333
BERT DeepWalk       6.166667
RoBERTa DeepWalk    6.333333
LLaMA TADW          7.166667
BERT SVD                 8.0
RoBERTa SVD              8.0
BERT Node2Vec       8.666667
LLaMA Baseline      8.833333
BERT Baseline       9.666667
RoBERTa Node2Vec   10.333333
RoBERTa Baseline   11.333333
RoBERTa TADW       13.666667
BERT TADW          13.833333
DeepSeek Baseline  15.166667
DeepSeek TADW      16.333333
DeepSeek SVD            17.0
DeepSeek Node2Vec  18.166667
DeepSeek DeepWalk  19.333333

### Predicción de Moral

In [4]:

# Macro F1 scores predicción de moral
macro_values = {
    'BERT': [ [12.82,22.59 , 30.45],
             [12.82, 26.21, 25.11],
             [12.82, 21.12, 34.11],
             [12.82, 23.45, 32.63],
             [12.82, 23.00, 24.65]
    ],
    'RoBERTa': [
        [12.82, 36.20, 44.67],
        [12.82, 34.92, 41.35],
        [12.82, 38.89, 47.41],
        [12.82, 38.88, 42.69],
        [12.82, 33.32, 27.38]
    ],
    'LLaMA': [
        [19.86, 23.02, 24.15],
        [12.00, 22.92, 27.77],
        [12.00, 23.59, 25.43],
        [12.24, 22.36, 27.05],
        [12.82, 28.70, 29.73]
    ],
    'DeepSeek': [
        [13.61, 16.06, 18.50],
        [19.74, 22.16, 19.94],
        [19.74, 19.42, 18.34],
        [19.74, 21.46, 21.33],
        [12.42, 16.02, 16.81]
    ]
}

a=0.05
modelos = ['BERT','RoBERTa', 'LLaMA', 'DeepSeek']
modelos = ['RoBERTa', 'LLaMA']
metodos = ['baselines','SVD', 'DeepWalk', 'Node2Vec', 'TADW']
datasets = ['RT-MIND', 'HCR', 'OMC']


rows = []
index = []

for modelo in modelos:
    for metodo, valores in zip(metodos, macro_values[modelo]):
        index.append((modelo, metodo))
        rows.append(valores)

multi_index = pd.MultiIndex.from_tuples(index, names=[None, None])
df = pd.DataFrame(rows, index=multi_index, columns=datasets)
df

                   RT-MIND    HCR    OMC
RoBERTa baselines    12.82  36.20  44.67
        SVD          12.82  34.92  41.35
        DeepWalk     12.82  38.89  47.41
        Node2Vec     12.82  38.88  42.69
        TADW         12.82  33.32  27.38
LLaMA   baselines    19.86  23.02  24.15
        SVD          12.00  22.92  27.77
        DeepWalk     12.00  23.59  25.43
        Node2Vec     12.24  22.36  27.05
        TADW         12.82  28.70  29.73

In [7]:

# Macro F1 scores predicción de moral
macro_values = {
    'RoBERTa': [
        [12.82, 36.20, 44.67],
        [12.82, 34.92, 41.35],
        [12.82, 38.89, 47.41],
        [12.82, 38.88, 42.69],
        [12.82, 33.32, 27.38]
    ],
    'LLaMA': [
        [19.86, 23.02, 24.15],
        [12.00, 22.92, 27.77],
        [12.00, 23.59, 25.43],
        [12.24, 22.36, 27.05],
        [12.82, 28.70, 29.73]
    ]
}

a=0.05
modelos = ['RoBERTa', 'LLaMA']
metodos = ['baselines','SVD', 'DeepWalk', 'Node2Vec', 'TADW']
datasets = ['RT-MIND', 'HCR', 'OMC']


rows = []
index = []

for modelo in modelos:
    for metodo, valores in zip(metodos, macro_values[modelo]):
        index.append((modelo, metodo))
        rows.append(valores)

multi_index = pd.MultiIndex.from_tuples(index, names=[None, None])
df = pd.DataFrame(rows, index=multi_index, columns=datasets)
df

                   RT-MIND    HCR    OMC
RoBERTa baselines    12.82  36.20  44.67
        SVD          12.82  34.92  41.35
        DeepWalk     12.82  38.89  47.41
        Node2Vec     12.82  38.88  42.69
        TADW         12.82  33.32  27.38
LLaMA   baselines    19.86  23.02  24.15
        SVD          12.00  22.92  27.77
        DeepWalk     12.00  23.59  25.43
        Node2Vec     12.24  22.36  27.05
        TADW         12.82  28.70  29.73

In [8]:
df = pd.DataFrame(rows, index=multi_index, columns=datasets)
df
df=df.reset_index()
df['features']=df['level_1']
df['classifier']=df['level_0']
df.drop(['level_0','level_1'], axis=1, inplace=True)
a=0.05
x, friedman_list = stats.main(df, a=a)
friedman_list

k: 10       N: 3       a: 0.05
chi2:  16.6
Friedman's F:  3.192307692307693
F(9,18)|0.05:  2.4562811491592678

                          0
RoBERTa DeepWalk   2.166667
RoBERTa baselines  3.166667
RoBERTa Node2Vec   3.166667
RoBERTa SVD        4.166667
LLaMA TADW         5.166667
RoBERTa TADW            5.5
LLaMA baselines    6.333333
LLaMA SVD          8.166667
LLaMA DeepWalk          8.5
LLaMA Node2Vec     8.666667

In [9]:
print(friedman_list.to_latex())

\begin{tabular}{ll}
\toprule
 & 0 \\
\midrule
RoBERTa DeepWalk & 2.166667 \\
RoBERTa baselines & 3.166667 \\
RoBERTa Node2Vec & 3.166667 \\
RoBERTa SVD & 4.166667 \\
LLaMA TADW & 5.166667 \\
RoBERTa TADW & 5.500000 \\
LLaMA baselines & 6.333333 \\
LLaMA SVD & 8.166667 \\
LLaMA DeepWalk & 8.500000 \\
LLaMA Node2Vec & 8.666667 \\
\bottomrule
\end{tabular}

---------------------------------------------

### Leer Ficheros

In [19]:
import os
file_name = "../data/MIND/F1_results/bert-base-morality2"
file_path = os.path.join(os.getcwd(), file_name)


with open(file_path, "r") as f:
    data = json.load(f)


macro_f1_list = []

for exp in data["experiments"]:
    experiment_name = exp["experiment"]
    dataset_name = exp["dataset"]
    macro_f1_score = exp["results"]["macro avg"]["f1-score"]

    macro_f1_list.append({
        "experiment": experiment_name,
        "dataset": dataset_name,
        "macro_f1": macro_f1_score
    })


df = pd.DataFrame(macro_f1_list)

df

   experiment dataset  macro_f1
0    baseline   pozzi  0.128205
1         svd   pozzi  0.128205
2    deepwalk   pozzi  0.128205
3    node2vec   pozzi  0.128205
4        tadw   pozzi  0.128205
5    baseline     hcr  0.225877
6         svd     hcr  0.262067
7    deepwalk     hcr  0.211211
8    node2vec     hcr  0.234533
9        tadw     hcr  0.230009
10   baseline     omc  0.304521
11        svd     omc  0.369118
12   deepwalk     omc  0.341097
13   node2vec     omc  0.326299
14       tadw     omc  0.246474

In [18]:
import os
import json
import pandas as pd


file_name = "../data/MIND/F1_results/bert-base-morality2"
file_path = os.path.join(os.getcwd(), file_name)


with open(file_path, "r") as f:
    data = json.load(f)

records = []

for exp in data["experiments"]:
    experiment_name = exp["experiment"]
    dataset_name = exp["dataset"]
    results = exp["results"]
    
    macro_f1 = results["macro avg"]["f1-score"]
    
    
    f1_class_0 = results.get("0", {}).get("f1-score", None)
    f1_class_1 = results.get("1", {}).get("f1-score", None)
    f1_class_2 = results.get("2", {}).get("f1-score", None)
    f1_class_3 = results.get("3", {}).get("f1-score", None)
    f1_class_4 = results.get("4", {}).get("f1-score", None)
    f1_class_5 = results.get("5", {}).get("f1-score", None)

    records.append({
        "experiment": experiment_name,
        "dataset": dataset_name,
        "f1_class_0": f1_class_0,
        "f1_class_1": f1_class_1,
        "f1_class_2": f1_class_2,
        "f1_class_3": f1_class_3,
        "f1_class_4": f1_class_4,
        "f1_class_5": f1_class_5,
        "macro_f1": macro_f1,
    })


df = pd.DataFrame(records)

df

,experiment,dataset,f1_class_0,f1_class_1,f1_class_2,f1_class_3,f1_class_4,f1_class_5,macro_f1
0,baseline,pozzi,0.769231,0.000000,0.000000,0.000000,0.000000,0.0,0.128205
1,svd,pozzi,0.769231,0.000000,0.000000,0.000000,0.000000,0.0,0.128205
2,deepwalk,pozzi,0.769231,0.000000,0.000000,0.000000,0.000000,0.0,0.128205
3,node2vec,pozzi,0.769231,0.000000,0.000000,0.000000,0.000000,0.0,0.128205
4,tadw,pozzi,0.769231,0.000000,0.000000,0.000000,0.000000,0.0,0.128205
5,baseline,hcr,0.850000,0.000000,0.400000,0.000000,0.105263,0.0,0.225877
6,svd,hcr,0.880829,0.000000,0.413793,0.166667,0.111111,0.0,0.262067
7,deepwalk,hcr,0.876289,0.000000,0.285714,0.000000,0.105263,0.0,0.211211
8,node2vec,hcr,0.877551,0.000000,0.347826,0.000000,0.181818,0.0,0.234533
9,tadw,hcr,0.890052,0.000000,0.240000,0.000000,0.250000,0.0,0.230009
10,baseline,omc,0.936102,0.416667,0.166667,0.000000,0.307692,0.0,0.304521
11,svd,omc,0.931818,0.571429,0.363636,0.000000,0.347826,0.0,0.369118
12,deepwalk,omc,0.935691,0.461538,0.363636,0.000000,0.285714,0.0,0.341097
13,node2vec,omc,0.940419,0.480000,0.181818,0.000000,0.355556,0.0,0.326299
14,tadw,omc,0.934400,0.444444,0.000000,0.000000,0.100000,0.0,0.246474

In [ ]:
#g¡